server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#debug: true


logging:
  level:
    com.xiao: debug
#  pattern:
#    file:
#  pattern:
#    console: xxxx
#  path: xxxx
spring:
  thymeleaf:
    cache: false

  messages:
    basename: i18n.loginv
