server:
  port: 8080
  servlet:
    context-path: /xiao

person:
  lastName: zhangsan
  age: 18
  boss: false
  birth: 2019/7/26
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: xiaogou
    age: 2